-- Run this once in the Supabase Dashboard: SQL Editor -> New query -> Run.
-- This schema is intentionally private: only the server-side service-role key
-- used by the monitor may access these tables.

create table if not exists public.companies (
  id bigint generated by default as identity primary key,
  name text not null unique,
  career_url text not null,
  enabled boolean not null default true,
  priority integer not null default 1,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  last_checked_at timestamptz,
  last_successful_check timestamptz,
  last_error text
);

create table if not exists public.jobs (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.companies(id) on delete cascade,
  identity text not null,
  external_job_id text,
  title text not null,
  location text,
  job_url text not null,
  description text,
  date_posted text,
  first_seen timestamptz not null,
  last_seen timestamptz not null,
  status text not null default 'active',
  relevance_score integer not null default 0,
  unique(company_id, identity)
);

create table if not exists public.company_checks (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.companies(id) on delete cascade,
  checked_at timestamptz not null,
  status text not null,
  jobs_found integer not null,
  new_jobs_found integer not null,
  response_code integer,
  scraper_type text,
  content_hash text,
  error_message text
);

alter table public.companies enable row level security;
alter table public.jobs enable row level security;
alter table public.company_checks enable row level security;
